#!/home/alayna/sel/ve/bin/python3
# -*- coding: utf-8 -*-

from selenium import webdriver
import time

try: 
    link = "http://suninjuly.github.io/registration2.html"
    browser = webdriver.Chrome()
    browser.get(link)
    input1 = browser.find_element_by_xpath("//input[@class='form-control first'][@placeholder='Input your first name']")
    input1.send_keys("Nikolay")
    input2 = browser.find_element_by_xpath("//input[@class='form-control second'][@placeholder='Input your last name']")
    input2.send_keys("Levchenkov")
    input3 = browser.find_element_by_xpath("//input[@class='form-control third'][@placeholder='Input your email']")
    input3.send_keys("kolyan@boss.com")
    button = browser.find_element_by_css_selector("button.btn")
    button.click()
    # ждем загрузки страницы
    time.sleep(1)
    welcome_text_elt = browser.find_element_by_tag_name("h1")
    welcome_text = welcome_text_elt.text
    assert "Congratulations! You have successfully registered!" == welcome_text

finally:
    time.sleep(10)
    browser.quit()